# /// script
# requires-python = ">=3.12"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Rebuild the `index.md` family of a wiki from the pages' YAML frontmatter.

The index is a **derived cache**, never a source of truth: frontmatter is
canonical, and this script turns it into Obsidian-navigable navigation files.
Delete every `index.md` and re-run — you get byte-identical files back.

Writes:
  wiki/index.md            the OKF bundle root (the one index with frontmatter)
  wiki/<subdir>/index.md   one `title — description` bullet per page, sorted by slug
  wiki/repos/index.md      every page under every repo dir, grouped by repo (added in 02)

Also runs an OKF conformance check (see CONVENTIONS.md § OKF alignment):
warnings go to stderr; a page missing a non-empty `type` is the only fatal error.

Usage:
  uv run --script build_index_md.py --wiki-dir ../../../../wiki-<slug>
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml

# Open Knowledge Format version declared by the bundle root.
OKF_VERSION = "0.1"

HEADER = "<!-- AUTOGENERATED by scripts/build_index_md.py — do not edit; your changes will be overwritten. -->\n\n"

# (subdirectory of wiki/, heading). One index.md per entry, when it holds pages.
SUBDIRS: list[tuple[str, str]] = [
    ("sources", "Sources"),
    ("entities", "Entities"),
    ("concepts", "Concepts"),
]

# <!-- added in 02 --> Subdirectories holding one directory per subject, whose pages
# get a single grouped index: wiki/repos/<repo>/*.md -> wiki/repos/index.md.
NESTED_SUBDIRS: list[tuple[str, str]] = [
    ("repos", "Repos"),
]

# Single pages sitting directly under wiki/, linked from the bundle root.
SINGLETONS: list[tuple[str, str]] = [
    ("overview.md", "Overview"),
]

# OKF §7: log headings lead with a bare ISO date, so `grep '^## 20'` finds them all.
LOG_HEADING_RE = re.compile(r"^##\s+\d{4}-\d{2}-\d{2}\b")


# ---------------------------------------------------------------- helpers ---


def one_line(value: Any, limit: int = 200) -> str:
    """Collapse a frontmatter value to a single index-safe line."""
    if not value:
        return ""
    text = " ".join(str(value).split())
    return text if len(text) <= limit else text[: limit - 3] + "..."


def wikilink(path: str, label: str) -> str:
    """Obsidian wikilink, path relative to the wiki dir, extension stripped."""
    target = path[:-3] if path.endswith(".md") else path
    return f"[[{target}|{label}]]"


def parse_frontmatter(path: Path) -> tuple[str, dict[str, Any]]:
    """Return (state, frontmatter); state is "ok", "absent" or "unparseable"."""
    try:
        text = path.read_text()
    except OSError:
        return "absent", {}
    if not text.startswith("---"):
        return "absent", {}
    lines = text.splitlines()
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return "absent", {}
    try:
        data = yaml.safe_load("\n".join(lines[1:end]))
    except yaml.YAMLError:
        return "unparseable", {}
    return ("ok", data) if isinstance(data, dict) else ("unparseable", {})


def page_files(directory: Path) -> list[Path]:
    """Sorted `.md` pages in a directory — index.md is reserved, never a page."""
    if not directory.is_dir():
        return []
    return sorted(p for p in directory.iterdir() if p.is_file() and p.suffix == ".md" and p.name != "index.md")


def nested_page_files(directory: Path) -> list[tuple[str, Path]]:
    """<!-- added in 02 --> (group, page) pairs one level deep, e.g. repos/<repo>/<page>.md."""
    if not directory.is_dir():
        return []
    return sorted(
        (group.name, page)
        for group in directory.iterdir()
        if group.is_dir()
        for page in page_files(group)
    )


def page_meta(path: Path) -> tuple[str, str]:
    """(title, description) for one page, straight from its frontmatter."""
    _, fm = parse_frontmatter(path)
    return str(fm.get("title") or path.stem), one_line(fm.get("description"))


def is_autogenerated(path: Path) -> bool:
    try:
        return "AUTOGENERATED" in path.read_text()[:200]
    except OSError:
        return False


# ------------------------------------------------------------- rendering ---


def render_subdir_index(bundle: Path, subdir: str, heading: str) -> str | None:
    """Content of `wiki/<subdir>/index.md`, or None when the subdir holds no pages."""
    files = page_files(bundle / subdir)
    if not files:
        return None
    bullets = []
    for f in files:
        title, description = page_meta(f)
        bullet = f"- {wikilink(f'wiki/{subdir}/{f.name}', title)}"
        bullets.append(f"{bullet} — {description}" if description else bullet)
    return f"{HEADER}# {heading}\n\n" + "\n".join(bullets) + "\n"


def render_nested_index(bundle: Path, subdir: str, heading: str) -> str | None:
    """<!-- added in 02 --> Content of `wiki/repos/index.md`, one section per repo."""
    entries = nested_page_files(bundle / subdir)
    if not entries:
        return None
    parts: list[str] = [HEADER, f"# {heading}\n"]
    current = None
    for group, page in entries:
        if group != current:
            parts.append(f"\n## {group}\n\n")
            current = group
        title, description = page_meta(page)
        bullet = f"- {wikilink(f'wiki/{subdir}/{group}/{page.name}', title)}"
        parts.append(f"{bullet} — {description}\n" if description else f"{bullet}\n")
    return "".join(parts)


def render_root_index(bundle: Path, slug: str) -> str:
    """Content of the OKF bundle root `wiki/index.md` — the only index with frontmatter."""
    blocks: list[str] = []

    singletons = [
        f"- {wikilink(f'wiki/{name}', label)}" for name, label in SINGLETONS if (bundle / name).is_file()
    ]
    if singletons:
        blocks.append("\n".join(singletons))

    browse = [
        f"- {wikilink(f'wiki/{subdir}/index.md', heading)} ({len(page_files(bundle / subdir))})"
        for subdir, heading in SUBDIRS
        if page_files(bundle / subdir)
    ]
    browse += [  # <!-- added in 02 -->
        f"- {wikilink(f'wiki/{subdir}/index.md', heading)} ({len(nested_page_files(bundle / subdir))})"
        for subdir, heading in NESTED_SUBDIRS
        if nested_page_files(bundle / subdir)
    ]
    if browse:
        blocks.append("## Browse\n\n" + "\n".join(browse))

    frontmatter = f'---\nokf_version: "{OKF_VERSION}"\ntitle: {slug} — Wiki\n---\n\n'
    body = "\n\n".join(blocks) + "\n" if blocks else "_Empty wiki._\n"
    return f"{frontmatter}{HEADER}# {slug} — Wiki\n\n{body}"


def write_indexes(bundle: Path, slug: str) -> list[Path]:
    """Write every index file. Returns the paths written, root last."""
    written: list[Path] = []
    for subdir, heading in SUBDIRS:
        target = bundle / subdir / "index.md"
        content = render_subdir_index(bundle, subdir, heading)
        if content is None:
            # Subdir emptied since the last run — drop our stale index.
            if target.is_file() and is_autogenerated(target):
                target.unlink()
            continue
        target.write_text(content)
        written.append(target)
    for subdir, heading in NESTED_SUBDIRS:  # <!-- added in 02 -->
        target = bundle / subdir / "index.md"
        content = render_nested_index(bundle, subdir, heading)
        if content is None:
            if target.is_file() and is_autogenerated(target):
                target.unlink()
            continue
        target.write_text(content)
        written.append(target)

    root = bundle / "index.md"
    root.write_text(render_root_index(bundle, slug))
    written.append(root)
    return written


# ----------------------------------------------------------- conformance ---


def check_conformance(wiki_dir: Path, bundle: Path) -> tuple[list[str], list[str]]:
    """Return (fatal, warnings) — see CONVENTIONS.md § OKF alignment."""
    fatal: list[str] = []
    warnings: list[str] = []
    root_index = bundle / "index.md"

    for path in sorted(bundle.rglob("*.md")):
        rel = path.relative_to(wiki_dir)
        if path.name == "index.md":
            # Only the bundle root may carry frontmatter (OKF §9.3).
            if path != root_index and path.read_text().startswith("---"):
                warnings.append(f"{rel}: a non-root index.md must not carry frontmatter")
            continue
        state, fm = parse_frontmatter(path)
        if state != "ok":
            fatal.append(f"{rel}: {state} YAML frontmatter")
            continue
        if not str(fm.get("type") or "").strip():
            fatal.append(f"{rel}: missing a non-empty `type`")
        if not str(fm.get("description") or "").strip():
            warnings.append(f"{rel}: missing `description` — its index bullet will be bare")

    log = wiki_dir / "log.md"
    if log.is_file():
        for n, line in enumerate(log.read_text(errors="replace").splitlines(), start=1):
            if line.startswith("## ") and not LOG_HEADING_RE.match(line):
                warnings.append(f"log.md:{n}: heading must lead with YYYY-MM-DD: {line.strip()!r}")
    return fatal, warnings


# ------------------------------------------------------------------ main ---


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--wiki-dir", required=True, help="Path to wiki-<slug>/ (the dir holding raw/, wiki/ and log.md).")
    args = parser.parse_args()

    wiki_dir = Path(args.wiki_dir).expanduser().resolve()
    bundle = wiki_dir / "wiki"
    if not bundle.is_dir():
        raise SystemExit(f"not a wiki dir (no wiki/ inside): {wiki_dir}")

    slug = wiki_dir.name.removeprefix("wiki-")
    written = write_indexes(bundle, slug)
    fatal, warnings = check_conformance(wiki_dir, bundle)

    for line in fatal:
        print(f"ERROR: {line}", file=sys.stderr)
    for line in warnings:
        print(f"WARN:  {line}", file=sys.stderr)

    print(
        json.dumps(
            {
                "wiki_dir": str(wiki_dir),
                "indexes_written": [str(p.relative_to(wiki_dir)) for p in written],
                "pages": sum(len(page_files(bundle / s)) for s, _ in SUBDIRS)
                + sum(len(nested_page_files(bundle / s)) for s, _ in NESTED_SUBDIRS),
                "errors": fatal,
                "warnings": warnings,
            },
            indent=2,
        )
    )
    if fatal:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
